disabled_rules:
    - trailing_whitespace                    
    - colon   
    - large_tuple        
    - function_parameter_count
    
excluded:
  - Carthage
  - Pods

force_cast: warning

force_try:
  severity: warning

line_length:
  - 160
  - 200

type_body_length:
  - 300 # warning
  - 400 # error

file_length:
  warning: 400
  error: 600

type_name:
  min_length: 3 
  max_length:
    warning: 40
    error: 50
  excluded: 
    - PH

identifier_name:
  min_length:
    error: 2
  excluded: 
    - id
    - x
    - y
    - iv

reporter: "xcode" 
